# =============================================================================
# tests/zknh_selfcheck.s: AUTO-GENERATED by tools/gen_selfcheck.py. The Zknh SHA-2
# instructions and the custom hsec.cteq (240 test cases), the worked example of
# docs/learn/10_adding_instructions.md. Same convention as isa_selfcheck.s:
#   PASS: tohost = 1           FAIL: tohost = (test number << 1) | 1
#
# EXPECT: a0 = 0
# =============================================================================
t1: # sha256sum0 0x0
    li   a0, 1
    li   a1, 0x0
    sha256sum0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t1_ok
    j    fail
t1_ok:
t2: # sha256sum0 0x1
    li   a0, 2
    li   a1, 0x1
    sha256sum0 a3, a1
    li   t6, 0x40080400
    beq  a3, t6, t2_ok
    j    fail
t2_ok:
t3: # sha256sum0 0xffffffffffffffff
    li   a0, 3
    li   a1, 0xffffffffffffffff
    sha256sum0 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t3_ok
    j    fail
t3_ok:
t4: # sha256sum0 0x7
    li   a0, 4
    li   a1, 0x7
    sha256sum0 a3, a1
    li   t6, 0xffffffffc0381c01
    beq  a3, t6, t4_ok
    j    fail
t4_ok:
t5: # sha256sum0 0xfffffffffffffff9
    li   a0, 5
    li   a1, 0xfffffffffffffff9
    sha256sum0 a3, a1
    li   t6, 0x7fcfe7fe
    beq  a3, t6, t5_ok
    j    fail
t5_ok:
t6: # sha256sum0 0x8000000000000000
    li   a0, 6
    li   a1, 0x8000000000000000
    sha256sum0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t6_ok
    j    fail
t6_ok:
t7: # sha256sum0 0x7fffffffffffffff
    li   a0, 7
    li   a1, 0x7fffffffffffffff
    sha256sum0 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t7_ok
    j    fail
t7_ok:
t8: # sha256sum0 0x80000000
    li   a0, 8
    li   a1, 0x80000000
    sha256sum0 a3, a1
    li   t6, 0x20040200
    beq  a3, t6, t8_ok
    j    fail
t8_ok:
t9: # sha256sum0 0x7fffffff
    li   a0, 9
    li   a1, 0x7fffffff
    sha256sum0 a3, a1
    li   t6, 0xffffffffdffbfdff
    beq  a3, t6, t9_ok
    j    fail
t9_ok:
t10: # sha256sum0 0xffffffff80000000
    li   a0, 10
    li   a1, 0xffffffff80000000
    sha256sum0 a3, a1
    li   t6, 0x20040200
    beq  a3, t6, t10_ok
    j    fail
t10_ok:
t11: # sha256sum0 0x123456789abcdef0
    li   a0, 11
    li   a1, 0x123456789abcdef0
    sha256sum0 a3, a1
    li   t6, 0x22502030
    beq  a3, t6, t11_ok
    j    fail
t11_ok:
t12: # sha256sum0 0xfedcba9876543210
    li   a0, 12
    li   a1, 0xfedcba9876543210
    sha256sum0 a3, a1
    li   t6, 0xffffffffdddefffc
    beq  a3, t6, t12_ok
    j    fail
t12_ok:
t13: # sha256sum0 0x3f
    li   a0, 13
    li   a1, 0x3f
    sha256sum0 a3, a1
    li   t6, 0xffffffffc1f8fc0f
    beq  a3, t6, t13_ok
    j    fail
t13_ok:
t14: # sha256sum0 0x40
    li   a0, 14
    li   a1, 0x40
    sha256sum0 a3, a1
    li   t6, 0x2010010
    beq  a3, t6, t14_ok
    j    fail
t14_ok:
t15: # sha256sum0 0x21
    li   a0, 15
    li   a1, 0x21
    sha256sum0 a3, a1
    li   t6, 0x41088408
    beq  a3, t6, t15_ok
    j    fail
t15_ok:
t16: # sha256sum0 0xff00ff00ff00ff
    li   a0, 16
    li   a1, 0xff00ff00ff00ff
    sha256sum0 a3, a1
    li   t6, 0x3bc43bc4
    beq  a3, t6, t16_ok
    j    fail
t16_ok:
t17: # sha256sum0 0x100000000
    li   a0, 17
    li   a1, 0x100000000
    sha256sum0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t17_ok
    j    fail
t17_ok:
t18: # sha256sum0 0x8000000000000001
    li   a0, 18
    li   a1, 0x8000000000000001
    sha256sum0 a3, a1
    li   t6, 0x40080400
    beq  a3, t6, t18_ok
    j    fail
t18_ok:
t19: # sha256sum0 0xffff8000
    li   a0, 19
    li   a1, 0xffff8000
    sha256sum0 a3, a1
    li   t6, 0xffffffffc1f81c03
    beq  a3, t6, t19_ok
    j    fail
t19_ok:
t20: # sha256sum0 0x102030400000080
    li   a0, 20
    li   a1, 0x102030400000080
    sha256sum0 a3, a1
    li   t6, 0x4020020
    beq  a3, t6, t20_ok
    j    fail
t20_ok:
t21: # sha256sum0 0x6a09e667
    li   a0, 21
    li   a1, 0x6a09e667
    sha256sum0 a3, a1
    li   t6, 0xffffffffce20b47e
    beq  a3, t6, t21_ok
    j    fail
t21_ok:
t22: # sha256sum0 0x510e527f
    li   a0, 22
    li   a1, 0x510e527f
    sha256sum0 a3, a1
    li   t6, 0x7ef0e1a9
    beq  a3, t6, t22_ok
    j    fail
t22_ok:
t23: # sha256sum0 0x6a09e667f3bcc908
    li   a0, 23
    li   a1, 0x6a09e667f3bcc908
    sha256sum0 a3, a1
    li   t6, 0xffffffff878c8c6a
    beq  a3, t6, t23_ok
    j    fail
t23_ok:
t24: # sha256sum0 0x61626380
    li   a0, 24
    li   a1, 0x61626380
    sha256sum0 a3, a1
    li   t6, 0xffffffff8dd59276
    beq  a3, t6, t24_ok
    j    fail
t24_ok:
t25: # sha256sum1 0x0
    li   a0, 25
    li   a1, 0x0
    sha256sum1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t25_ok
    j    fail
t25_ok:
t26: # sha256sum1 0x1
    li   a0, 26
    li   a1, 0x1
    sha256sum1 a3, a1
    li   t6, 0x4200080
    beq  a3, t6, t26_ok
    j    fail
t26_ok:
t27: # sha256sum1 0xffffffffffffffff
    li   a0, 27
    li   a1, 0xffffffffffffffff
    sha256sum1 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t27_ok
    j    fail
t27_ok:
t28: # sha256sum1 0x7
    li   a0, 28
    li   a1, 0x7
    sha256sum1 a3, a1
    li   t6, 0x1ce00380
    beq  a3, t6, t28_ok
    j    fail
t28_ok:
t29: # sha256sum1 0xfffffffffffffff9
    li   a0, 29
    li   a1, 0xfffffffffffffff9
    sha256sum1 a3, a1
    li   t6, 0xffffffffe73ffcff
    beq  a3, t6, t29_ok
    j    fail
t29_ok:
t30: # sha256sum1 0x8000000000000000
    li   a0, 30
    li   a1, 0x8000000000000000
    sha256sum1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t30_ok
    j    fail
t30_ok:
t31: # sha256sum1 0x7fffffffffffffff
    li   a0, 31
    li   a1, 0x7fffffffffffffff
    sha256sum1 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t31_ok
    j    fail
t31_ok:
t32: # sha256sum1 0x80000000
    li   a0, 32
    li   a1, 0x80000000
    sha256sum1 a3, a1
    li   t6, 0x2100040
    beq  a3, t6, t32_ok
    j    fail
t32_ok:
t33: # sha256sum1 0x7fffffff
    li   a0, 33
    li   a1, 0x7fffffff
    sha256sum1 a3, a1
    li   t6, 0xfffffffffdefffbf
    beq  a3, t6, t33_ok
    j    fail
t33_ok:
t34: # sha256sum1 0xffffffff80000000
    li   a0, 34
    li   a1, 0xffffffff80000000
    sha256sum1 a3, a1
    li   t6, 0x2100040
    beq  a3, t6, t34_ok
    j    fail
t34_ok:
t35: # sha256sum1 0x123456789abcdef0
    li   a0, 35
    li   a1, 0x123456789abcdef0
    sha256sum1 a3, a1
    li   t6, 0x4216dcad
    beq  a3, t6, t35_ok
    j    fail
t35_ok:
t36: # sha256sum1 0xfedcba9876543210
    li   a0, 36
    li   a1, 0xfedcba9876543210
    sha256sum1 a3, a1
    li   t6, 0x29ce9275
    beq  a3, t6, t36_ok
    j    fail
t36_ok:
t37: # sha256sum1 0x3f
    li   a0, 37
    li   a1, 0x3f
    sha256sum1 a3, a1
    li   t6, 0xfffffffffbe01f80
    beq  a3, t6, t37_ok
    j    fail
t37_ok:
t38: # sha256sum1 0x40
    li   a0, 38
    li   a1, 0x40
    sha256sum1 a3, a1
    li   t6, 0x8002001
    beq  a3, t6, t38_ok
    j    fail
t38_ok:
t39: # sha256sum1 0x21
    li   a0, 39
    li   a1, 0x21
    sha256sum1 a3, a1
    li   t6, 0xffffffff80201080
    beq  a3, t6, t39_ok
    j    fail
t39_ok:
t40: # sha256sum1 0xff00ff00ff00ff
    li   a0, 40
    li   a1, 0xff00ff00ff00ff
    sha256sum1 a3, a1
    li   t6, 0xffffffff9c639c63
    beq  a3, t6, t40_ok
    j    fail
t40_ok:
t41: # sha256sum1 0x100000000
    li   a0, 41
    li   a1, 0x100000000
    sha256sum1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t41_ok
    j    fail
t41_ok:
t42: # sha256sum1 0x8000000000000001
    li   a0, 42
    li   a1, 0x8000000000000001
    sha256sum1 a3, a1
    li   t6, 0x4200080
    beq  a3, t6, t42_ok
    j    fail
t42_ok:
t43: # sha256sum1 0xffff8000
    li   a0, 43
    li   a1, 0xffff8000
    sha256sum1 a3, a1
    li   t6, 0xfffffffffc20018f
    beq  a3, t6, t43_ok
    j    fail
t43_ok:
t44: # sha256sum1 0x102030400000080
    li   a0, 44
    li   a1, 0x102030400000080
    sha256sum1 a3, a1
    li   t6, 0x10004002
    beq  a3, t6, t44_ok
    j    fail
t44_ok:
t45: # sha256sum1 0x6a09e667
    li   a0, 45
    li   a1, 0x6a09e667
    sha256sum1 a3, a1
    li   t6, 0x55b65510
    beq  a3, t6, t45_ok
    j    fail
t45_ok:
t46: # sha256sum1 0x510e527f
    li   a0, 46
    li   a1, 0x510e527f
    sha256sum1 a3, a1
    li   t6, 0x3587272b
    beq  a3, t6, t46_ok
    j    fail
t46_ok:
t47: # sha256sum1 0x6a09e667f3bcc908
    li   a0, 47
    li   a1, 0x6a09e667f3bcc908
    sha256sum1 a3, a1
    li   t6, 0xffffffffdcb400c4
    beq  a3, t6, t47_ok
    j    fail
t47_ok:
t48: # sha256sum1 0x61626380
    li   a0, 48
    li   a1, 0x61626380
    sha256sum1 a3, a1
    li   t6, 0xffffffffc0b865f2
    beq  a3, t6, t48_ok
    j    fail
t48_ok:
t49: # sha256sig0 0x0
    li   a0, 49
    li   a1, 0x0
    sha256sig0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t49_ok
    j    fail
t49_ok:
t50: # sha256sig0 0x1
    li   a0, 50
    li   a1, 0x1
    sha256sig0 a3, a1
    li   t6, 0x2004000
    beq  a3, t6, t50_ok
    j    fail
t50_ok:
t51: # sha256sig0 0xffffffffffffffff
    li   a0, 51
    li   a1, 0xffffffffffffffff
    sha256sig0 a3, a1
    li   t6, 0x1fffffff
    beq  a3, t6, t51_ok
    j    fail
t51_ok:
t52: # sha256sig0 0x7
    li   a0, 52
    li   a1, 0x7
    sha256sig0 a3, a1
    li   t6, 0xe01c000
    beq  a3, t6, t52_ok
    j    fail
t52_ok:
t53: # sha256sig0 0xfffffffffffffff9
    li   a0, 53
    li   a1, 0xfffffffffffffff9
    sha256sig0 a3, a1
    li   t6, 0x13fe7fff
    beq  a3, t6, t53_ok
    j    fail
t53_ok:
t54: # sha256sig0 0x8000000000000000
    li   a0, 54
    li   a1, 0x8000000000000000
    sha256sig0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t54_ok
    j    fail
t54_ok:
t55: # sha256sig0 0x7fffffffffffffff
    li   a0, 55
    li   a1, 0x7fffffffffffffff
    sha256sig0 a3, a1
    li   t6, 0x1fffffff
    beq  a3, t6, t55_ok
    j    fail
t55_ok:
t56: # sha256sig0 0x80000000
    li   a0, 56
    li   a1, 0x80000000
    sha256sig0 a3, a1
    li   t6, 0x11002000
    beq  a3, t6, t56_ok
    j    fail
t56_ok:
t57: # sha256sig0 0x7fffffff
    li   a0, 57
    li   a1, 0x7fffffff
    sha256sig0 a3, a1
    li   t6, 0xeffdfff
    beq  a3, t6, t57_ok
    j    fail
t57_ok:
t58: # sha256sig0 0xffffffff80000000
    li   a0, 58
    li   a1, 0xffffffff80000000
    sha256sig0 a3, a1
    li   t6, 0x11002000
    beq  a3, t6, t58_ok
    j    fail
t58_ok:
t59: # sha256sig0 0x123456789abcdef0
    li   a0, 59
    li   a1, 0x123456789abcdef0
    sha256sig0 a3, a1
    li   t6, 0xffffffffc5dec4cc
    beq  a3, t6, t59_ok
    j    fail
t59_ok:
t60: # sha256sig0 0xfedcba9876543210
    li   a0, 60
    li   a1, 0xfedcba9876543210
    sha256sig0 a3, a1
    li   t6, 0x22a233b3
    beq  a3, t6, t60_ok
    j    fail
t60_ok:
t61: # sha256sig0 0x3f
    li   a0, 61
    li   a1, 0x3f
    sha256sig0 a3, a1
    li   t6, 0x7e0fc007
    beq  a3, t6, t61_ok
    j    fail
t61_ok:
t62: # sha256sig0 0x40
    li   a0, 62
    li   a1, 0x40
    sha256sig0 a3, a1
    li   t6, 0xffffffff80100008
    beq  a3, t6, t62_ok
    j    fail
t62_ok:
t63: # sha256sig0 0x21
    li   a0, 63
    li   a1, 0x21
    sha256sig0 a3, a1
    li   t6, 0x42084004
    beq  a3, t6, t63_ok
    j    fail
t63_ok:
t64: # sha256sig0 0xff00ff00ff00ff
    li   a0, 64
    li   a1, 0xff00ff00ff00ff
    sha256sig0 a3, a1
    li   t6, 0x3e21de21
    beq  a3, t6, t64_ok
    j    fail
t64_ok:
t65: # sha256sig0 0x100000000
    li   a0, 65
    li   a1, 0x100000000
    sha256sig0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t65_ok
    j    fail
t65_ok:
t66: # sha256sig0 0x8000000000000001
    li   a0, 66
    li   a1, 0x8000000000000001
    sha256sig0 a3, a1
    li   t6, 0x2004000
    beq  a3, t6, t66_ok
    j    fail
t66_ok:
t67: # sha256sig0 0xffff8000
    li   a0, 67
    li   a1, 0xffff8000
    sha256sig0 a3, a1
    li   t6, 0xfffffffffe0030ff
    beq  a3, t6, t67_ok
    j    fail
t67_ok:
t68: # sha256sig0 0x102030400000080
    li   a0, 68
    li   a1, 0x102030400000080
    sha256sig0 a3, a1
    li   t6, 0x200011
    beq  a3, t6, t68_ok
    j    fail
t68_ok:
t69: # sha256sig0 0x6a09e667
    li   a0, 69
    li   a1, 0x6a09e667
    sha256sig0 a3, a1
    li   t6, 0xffffffffba0cf582
    beq  a3, t6, t69_ok
    j    fail
t69_ok:
t70: # sha256sig0 0x510e527f
    li   a0, 70
    li   a1, 0x510e527f
    sha256sig0 a3, a1
    li   t6, 0x601c02a8
    beq  a3, t6, t70_ok
    j    fail
t70_ok:
t71: # sha256sig0 0x6a09e667f3bcc908
    li   a0, 71
    li   a1, 0x6a09e667f3bcc908
    sha256sig0 a3, a1
    li   t6, 0x3dd2dc5c
    beq  a3, t6, t71_ok
    j    fail
t71_ok:
t72: # sha256sig0 0x61626380
    li   a0, 72
    li   a1, 0x61626380
    sha256sig0 a3, a1
    li   t6, 0xffffffff940e90ef
    beq  a3, t6, t72_ok
    j    fail
t72_ok:
t73: # sha256sig1 0x0
    li   a0, 73
    li   a1, 0x0
    sha256sig1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t73_ok
    j    fail
t73_ok:
t74: # sha256sig1 0x1
    li   a0, 74
    li   a1, 0x1
    sha256sig1 a3, a1
    li   t6, 0xa000
    beq  a3, t6, t74_ok
    j    fail
t74_ok:
t75: # sha256sig1 0xffffffffffffffff
    li   a0, 75
    li   a1, 0xffffffffffffffff
    sha256sig1 a3, a1
    li   t6, 0x3fffff
    beq  a3, t6, t75_ok
    j    fail
t75_ok:
t76: # sha256sig1 0x7
    li   a0, 76
    li   a1, 0x7
    sha256sig1 a3, a1
    li   t6, 0x36000
    beq  a3, t6, t76_ok
    j    fail
t76_ok:
t77: # sha256sig1 0xfffffffffffffff9
    li   a0, 77
    li   a1, 0xfffffffffffffff9
    sha256sig1 a3, a1
    li   t6, 0x3c3fff
    beq  a3, t6, t77_ok
    j    fail
t77_ok:
t78: # sha256sig1 0x8000000000000000
    li   a0, 78
    li   a1, 0x8000000000000000
    sha256sig1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t78_ok
    j    fail
t78_ok:
t79: # sha256sig1 0x7fffffffffffffff
    li   a0, 79
    li   a1, 0x7fffffffffffffff
    sha256sig1 a3, a1
    li   t6, 0x3fffff
    beq  a3, t6, t79_ok
    j    fail
t79_ok:
t80: # sha256sig1 0x80000000
    li   a0, 80
    li   a1, 0x80000000
    sha256sig1 a3, a1
    li   t6, 0x205000
    beq  a3, t6, t80_ok
    j    fail
t80_ok:
t81: # sha256sig1 0x7fffffff
    li   a0, 81
    li   a1, 0x7fffffff
    sha256sig1 a3, a1
    li   t6, 0x1fafff
    beq  a3, t6, t81_ok
    j    fail
t81_ok:
t82: # sha256sig1 0xffffffff80000000
    li   a0, 82
    li   a1, 0xffffffff80000000
    sha256sig1 a3, a1
    li   t6, 0x205000
    beq  a3, t6, t82_ok
    j    fail
t82_ok:
t83: # sha256sig1 0x123456789abcdef0
    li   a0, 83
    li   a1, 0x123456789abcdef0
    sha256sig1 a3, a1
    li   t6, 0xfffffffff480f13e
    beq  a3, t6, t83_ok
    j    fail
t83_ok:
t84: # sha256sig1 0xfedcba9876543210
    li   a0, 84
    li   a1, 0xfedcba9876543210
    sha256sig1 a3, a1
    li   t6, 0xffffffff9f57a0ec
    beq  a3, t6, t84_ok
    j    fail
t84_ok:
t85: # sha256sig1 0x3f
    li   a0, 85
    li   a1, 0x3f
    sha256sig1 a3, a1
    li   t6, 0x186000
    beq  a3, t6, t85_ok
    j    fail
t85_ok:
t86: # sha256sig1 0x40
    li   a0, 86
    li   a1, 0x40
    sha256sig1 a3, a1
    li   t6, 0x280000
    beq  a3, t6, t86_ok
    j    fail
t86_ok:
t87: # sha256sig1 0x21
    li   a0, 87
    li   a1, 0x21
    sha256sig1 a3, a1
    li   t6, 0x14a000
    beq  a3, t6, t87_ok
    j    fail
t87_ok:
t88: # sha256sig1 0xff00ff00ff00ff
    li   a0, 88
    li   a1, 0xff00ff00ff00ff
    sha256sig1 a3, a1
    li   t6, 0x60605fa0
    beq  a3, t6, t88_ok
    j    fail
t88_ok:
t89: # sha256sig1 0x100000000
    li   a0, 89
    li   a1, 0x100000000
    sha256sig1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t89_ok
    j    fail
t89_ok:
t90: # sha256sig1 0x8000000000000001
    li   a0, 90
    li   a1, 0x8000000000000001
    sha256sig1 a3, a1
    li   t6, 0xa000
    beq  a3, t6, t90_ok
    j    fail
t90_ok:
t91: # sha256sig1 0xffff8000
    li   a0, 91
    li   a1, 0xffff8000
    sha256sig1 a3, a1
    li   t6, 0x303f9fe0
    beq  a3, t6, t91_ok
    j    fail
t91_ok:
t92: # sha256sig1 0x102030400000080
    li   a0, 92
    li   a1, 0x102030400000080
    sha256sig1 a3, a1
    li   t6, 0x500000
    beq  a3, t6, t92_ok
    j    fail
t92_ok:
t93: # sha256sig1 0x6a09e667
    li   a0, 93
    li   a1, 0x6a09e667
    sha256sig1 a3, a1
    li   t6, 0xffffffffcfe5da3c
    beq  a3, t6, t93_ok
    j    fail
t93_ok:
t94: # sha256sig1 0x510e527f
    li   a0, 94
    li   a1, 0x510e527f
    sha256sig1 a3, a1
    li   t6, 0xffffffffe3640132
    beq  a3, t6, t94_ok
    j    fail
t94_ok:
t95: # sha256sig1 0x6a09e667f3bcc908
    li   a0, 95
    li   a1, 0x6a09e667f3bcc908
    sha256sig1 a3, a1
    li   t6, 0xfffffffffd99889b
    beq  a3, t6, t95_ok
    j    fail
t95_ok:
t96: # sha256sig1 0x61626380
    li   a0, 96
    li   a1, 0x61626380
    sha256sig1 a3, a1
    li   t6, 0x7da86405
    beq  a3, t6, t96_ok
    j    fail
t96_ok:
t97: # sha512sum0 0x0
    li   a0, 97
    li   a1, 0x0
    sha512sum0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t97_ok
    j    fail
t97_ok:
t98: # sha512sum0 0x1
    li   a0, 98
    li   a1, 0x1
    sha512sum0 a3, a1
    li   t6, 0x1042000000
    beq  a3, t6, t98_ok
    j    fail
t98_ok:
t99: # sha512sum0 0xffffffffffffffff
    li   a0, 99
    li   a1, 0xffffffffffffffff
    sha512sum0 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t99_ok
    j    fail
t99_ok:
t100: # sha512sum0 0x7
    li   a0, 100
    li   a1, 0x7
    sha512sum0 a3, a1
    li   t6, 0x71ce000000
    beq  a3, t6, t100_ok
    j    fail
t100_ok:
t101: # sha512sum0 0xfffffffffffffff9
    li   a0, 101
    li   a1, 0xfffffffffffffff9
    sha512sum0 a3, a1
    li   t6, 0xffffff9e73ffffff
    beq  a3, t6, t101_ok
    j    fail
t101_ok:
t102: # sha512sum0 0x8000000000000000
    li   a0, 102
    li   a1, 0x8000000000000000
    sha512sum0 a3, a1
    li   t6, 0x821000000
    beq  a3, t6, t102_ok
    j    fail
t102_ok:
t103: # sha512sum0 0x7fffffffffffffff
    li   a0, 103
    li   a1, 0x7fffffffffffffff
    sha512sum0 a3, a1
    li   t6, 0xfffffff7deffffff
    beq  a3, t6, t103_ok
    j    fail
t103_ok:
t104: # sha512sum0 0x80000000
    li   a0, 104
    li   a1, 0x80000000
    sha512sum0 a3, a1
    li   t6, 0x2100000000000008
    beq  a3, t6, t104_ok
    j    fail
t104_ok:
t105: # sha512sum0 0x7fffffff
    li   a0, 105
    li   a1, 0x7fffffff
    sha512sum0 a3, a1
    li   t6, 0xe0fffff03e000007
    beq  a3, t6, t105_ok
    j    fail
t105_ok:
t106: # sha512sum0 0xffffffff80000000
    li   a0, 106
    li   a1, 0xffffffff80000000
    sha512sum0 a3, a1
    li   t6, 0x1f00000fc1fffff8
    beq  a3, t6, t106_ok
    j    fail
t106_ok:
t107: # sha512sum0 0x123456789abcdef0
    li   a0, 107
    li   a1, 0x123456789abcdef0
    sha512sum0 a3, a1
    li   t6, 0x7c57a100c7ec1abb
    beq  a3, t6, t107_ok
    j    fail
t107_ok:
t108: # sha512sum0 0xfedcba9876543210
    li   a0, 108
    li   a1, 0xfedcba9876543210
    sha512sum0 a3, a1
    li   t6, 0x483a85eff3813e54
    beq  a3, t6, t108_ok
    j    fail
t108_ok:
t109: # sha512sum0 0x3f
    li   a0, 109
    li   a1, 0x3f
    sha512sum0 a3, a1
    li   t6, 0x3ffbe000000
    beq  a3, t6, t109_ok
    j    fail
t109_ok:
t110: # sha512sum0 0x40
    li   a0, 110
    li   a1, 0x40
    sha512sum0 a3, a1
    li   t6, 0x41080000000
    beq  a3, t6, t110_ok
    j    fail
t110_ok:
t111: # sha512sum0 0x21
    li   a0, 111
    li   a1, 0x21
    sha512sum0 a3, a1
    li   t6, 0x21802000000
    beq  a3, t6, t111_ok
    j    fail
t111_ok:
t112: # sha512sum0 0xff00ff00ff00ff
    li   a0, 112
    li   a1, 0xff00ff00ff00ff
    sha512sum0 a3, a1
    li   t6, 0x31ce31ce31ce31ce
    beq  a3, t6, t112_ok
    j    fail
t112_ok:
t113: # sha512sum0 0x100000000
    li   a0, 113
    li   a1, 0x100000000
    sha512sum0 a3, a1
    li   t6, 0x4200000000000010
    beq  a3, t6, t113_ok
    j    fail
t113_ok:
t114: # sha512sum0 0x8000000000000001
    li   a0, 114
    li   a1, 0x8000000000000001
    sha512sum0 a3, a1
    li   t6, 0x1863000000
    beq  a3, t6, t114_ok
    j    fail
t114_ok:
t115: # sha512sum0 0xffff8000
    li   a0, 115
    li   a1, 0xffff8000
    sha512sum0 a3, a1
    li   t6, 0xc1f81f000000000f
    beq  a3, t6, t115_ok
    j    fail
t115_ok:
t116: # sha512sum0 0x102030400000080
    li   a0, 116
    li   a1, 0x102030400000080
    sha512sum0 a3, a1
    li   t6, 0x80008211062b487
    beq  a3, t6, t116_ok
    j    fail
t116_ok:
t117: # sha512sum0 0x6a09e667
    li   a0, 117
    li   a1, 0x6a09e667
    sha512sum0 a3, a1
    li   t6, 0xbac80c250e000006
    beq  a3, t6, t117_ok
    j    fail
t117_ok:
t118: # sha512sum0 0x510e527f
    li   a0, 118
    li   a1, 0x510e527f
    sha512sum0 a3, a1
    li   t6, 0x404afcb3e000005
    beq  a3, t6, t118_ok
    j    fail
t118_ok:
t119: # sha512sum0 0x6a09e667f3bcc908
    li   a0, 119
    li   a1, 0x6a09e667f3bcc908
    sha512sum0 a3, a1
    li   t6, 0x8c4db56aac80c2a
    beq  a3, t6, t119_ok
    j    fail
t119_ok:
t120: # sha512sum0 0x61626380
    li   a0, 120
    li   a1, 0x61626380
    sha512sum0 a3, a1
    li   t6, 0xebc642700000006
    beq  a3, t6, t120_ok
    j    fail
t120_ok:
t121: # sha512sum1 0x0
    li   a0, 121
    li   a1, 0x0
    sha512sum1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t121_ok
    j    fail
t121_ok:
t122: # sha512sum1 0x1
    li   a0, 122
    li   a1, 0x1
    sha512sum1 a3, a1
    li   t6, 0x4400000800000
    beq  a3, t6, t122_ok
    j    fail
t122_ok:
t123: # sha512sum1 0xffffffffffffffff
    li   a0, 123
    li   a1, 0xffffffffffffffff
    sha512sum1 a3, a1
    li   t6, 0xffffffffffffffff
    beq  a3, t6, t123_ok
    j    fail
t123_ok:
t124: # sha512sum1 0x7
    li   a0, 124
    li   a1, 0x7
    sha512sum1 a3, a1
    li   t6, 0x1dc00003800000
    beq  a3, t6, t124_ok
    j    fail
t124_ok:
t125: # sha512sum1 0xfffffffffffffff9
    li   a0, 125
    li   a1, 0xfffffffffffffff9
    sha512sum1 a3, a1
    li   t6, 0xffe67ffffcffffff
    beq  a3, t6, t125_ok
    j    fail
t125_ok:
t126: # sha512sum1 0x8000000000000000
    li   a0, 126
    li   a1, 0x8000000000000000
    sha512sum1 a3, a1
    li   t6, 0x2200000400000
    beq  a3, t6, t126_ok
    j    fail
t126_ok:
t127: # sha512sum1 0x7fffffffffffffff
    li   a0, 127
    li   a1, 0x7fffffffffffffff
    sha512sum1 a3, a1
    li   t6, 0xfffddfffffbfffff
    beq  a3, t6, t127_ok
    j    fail
t127_ok:
t128: # sha512sum1 0x80000000
    li   a0, 128
    li   a1, 0x80000000
    sha512sum1 a3, a1
    li   t6, 0x40000000022000
    beq  a3, t6, t128_ok
    j    fail
t128_ok:
t129: # sha512sum1 0x7fffffff
    li   a0, 129
    li   a1, 0x7fffffff
    sha512sum1 a3, a1
    li   t6, 0x3c3fffff81e000
    beq  a3, t6, t129_ok
    j    fail
t129_ok:
t130: # sha512sum1 0xffffffff80000000
    li   a0, 130
    li   a1, 0xffffffff80000000
    sha512sum1 a3, a1
    li   t6, 0xffc3c000007e1fff
    beq  a3, t6, t130_ok
    j    fail
t130_ok:
t131: # sha512sum1 0x123456789abcdef0
    li   a0, 131
    li   a1, 0x123456789abcdef0
    sha512sum1 a3, a1
    li   t6, 0x7031123334755677
    beq  a3, t6, t131_ok
    j    fail
t131_ok:
t132: # sha512sum1 0xfedcba9876543210
    li   a0, 132
    li   a1, 0xfedcba9876543210
    sha512sum1 a3, a1
    li   t6, 0x88fceedcccb8aa98
    beq  a3, t6, t132_ok
    j    fail
t132_ok:
t133: # sha512sum1 0x3f
    li   a0, 133
    li   a1, 0x3f
    sha512sum1 a3, a1
    li   t6, 0xf3c0001f800000
    beq  a3, t6, t133_ok
    j    fail
t133_ok:
t134: # sha512sum1 0x40
    li   a0, 134
    li   a1, 0x40
    sha512sum1 a3, a1
    li   t6, 0x110000020000000
    beq  a3, t6, t134_ok
    j    fail
t134_ok:
t135: # sha512sum1 0x21
    li   a0, 135
    li   a1, 0x21
    sha512sum1 a3, a1
    li   t6, 0x8c400010800000
    beq  a3, t6, t135_ok
    j    fail
t135_ok:
t136: # sha512sum1 0xff00ff00ff00ff
    li   a0, 136
    li   a1, 0xff00ff00ff00ff
    sha512sum1 a3, a1
    li   t6, 0xbc43bc43bc43bc43
    beq  a3, t6, t136_ok
    j    fail
t136_ok:
t137: # sha512sum1 0x100000000
    li   a0, 137
    li   a1, 0x100000000
    sha512sum1 a3, a1
    li   t6, 0x80000000044000
    beq  a3, t6, t137_ok
    j    fail
t137_ok:
t138: # sha512sum1 0x8000000000000001
    li   a0, 138
    li   a1, 0x8000000000000001
    sha512sum1 a3, a1
    li   t6, 0x6600000c00000
    beq  a3, t6, t138_ok
    j    fail
t138_ok:
t139: # sha512sum1 0xffff8000
    li   a0, 139
    li   a1, 0xffff8000
    sha512sum1 a3, a1
    li   t6, 0xe07fffc00003c001
    beq  a3, t6, t139_ok
    j    fail
t139_ok:
t140: # sha512sum1 0x102030400000080
    li   a0, 140
    li   a1, 0x102030400000080
    sha512sum1 a3, a1
    li   t6, 0x80200448ccd18101
    beq  a3, t6, t140_ok
    j    fail
t140_ok:
t141: # sha512sum1 0x6a09e667
    li   a0, 141
    li   a1, 0x6a09e667
    sha512sum1 a3, a1
    li   t6, 0xe030c4f33381b2a5
    beq  a3, t6, t141_ok
    j    fail
t141_ok:
t142: # sha512sum1 0x510e527f
    li   a0, 142
    li   a1, 0x510e527f
    sha512sum1 a3, a1
    li   t6, 0xdd4b47293f81507a
    beq  a3, t6, t142_ok
    j    fail
t142_ok:
t143: # sha512sum1 0x6a09e667f3bcc908
    li   a0, 143
    li   a1, 0x6a09e667f3bcc908
    sha512sum1 a3, a1
    li   t6, 0x259a6cc1643336ef
    beq  a3, t6, t143_ok
    j    fail
t143_ok:
t144: # sha512sum1 0x61626380
    li   a0, 144
    li   a1, 0x61626380
    sha512sum1 a3, a1
    li   t6, 0x16d0b131c0019dd1
    beq  a3, t6, t144_ok
    j    fail
t144_ok:
t145: # sha512sig0 0x0
    li   a0, 145
    li   a1, 0x0
    sha512sig0 a3, a1
    li   t6, 0x0
    beq  a3, t6, t145_ok
    j    fail
t145_ok:
t146: # sha512sig0 0x1
    li   a0, 146
    li   a1, 0x1
    sha512sig0 a3, a1
    li   t6, 0x8100000000000000
    beq  a3, t6, t146_ok
    j    fail
t146_ok:
t147: # sha512sig0 0xffffffffffffffff
    li   a0, 147
    li   a1, 0xffffffffffffffff
    sha512sig0 a3, a1
    li   t6, 0x1ffffffffffffff
    beq  a3, t6, t147_ok
    j    fail
t147_ok:
t148: # sha512sig0 0x7
    li   a0, 148
    li   a1, 0x7
    sha512sig0 a3, a1
    li   t6, 0x8700000000000003
    beq  a3, t6, t148_ok
    j    fail
t148_ok:
t149: # sha512sig0 0xfffffffffffffff9
    li   a0, 149
    li   a1, 0xfffffffffffffff9
    sha512sig0 a3, a1
    li   t6, 0x7fffffffffffffc
    beq  a3, t6, t149_ok
    j    fail
t149_ok:
t150: # sha512sig0 0x8000000000000000
    li   a0, 150
    li   a1, 0x8000000000000000
    sha512sig0 a3, a1
    li   t6, 0x4180000000000000
    beq  a3, t6, t150_ok
    j    fail
t150_ok:
t151: # sha512sig0 0x7fffffffffffffff
    li   a0, 151
    li   a1, 0x7fffffffffffffff
    sha512sig0 a3, a1
    li   t6, 0x407fffffffffffff
    beq  a3, t6, t151_ok
    j    fail
t151_ok:
t152: # sha512sig0 0x80000000
    li   a0, 152
    li   a1, 0x80000000
    sha512sig0 a3, a1
    li   t6, 0x41800000
    beq  a3, t6, t152_ok
    j    fail
t152_ok:
t153: # sha512sig0 0x7fffffff
    li   a0, 153
    li   a1, 0x7fffffff
    sha512sig0 a3, a1
    li   t6, 0x7f0000003f7fffff
    beq  a3, t6, t153_ok
    j    fail
t153_ok:
t154: # sha512sig0 0xffffffff80000000
    li   a0, 154
    li   a1, 0xffffffff80000000
    sha512sig0 a3, a1
    li   t6, 0x7effffffc0800000
    beq  a3, t6, t154_ok
    j    fail
t154_ok:
t155: # sha512sig0 0x123456789abcdef0
    li   a0, 155
    li   a1, 0x123456789abcdef0
    sha512sig0 a3, a1
    li   t6, 0xf92c77c6c4f1aa1b
    beq  a3, t6, t155_ok
    j    fail
t155_ok:
t156: # sha512sig0 0xfedcba9876543210
    li   a0, 156
    li   a1, 0xfedcba9876543210
    sha512sig0 a3, a1
    li   t6, 0x6e6d388393b0e55e
    beq  a3, t6, t156_ok
    j    fail
t156_ok:
t157: # sha512sig0 0x3f
    li   a0, 157
    li   a1, 0x3f
    sha512sig0 a3, a1
    li   t6, 0xbf0000000000001f
    beq  a3, t6, t157_ok
    j    fail
t157_ok:
t158: # sha512sig0 0x40
    li   a0, 158
    li   a1, 0x40
    sha512sig0 a3, a1
    li   t6, 0x4000000000000020
    beq  a3, t6, t158_ok
    j    fail
t158_ok:
t159: # sha512sig0 0x21
    li   a0, 159
    li   a1, 0x21
    sha512sig0 a3, a1
    li   t6, 0xa100000000000010
    beq  a3, t6, t159_ok
    j    fail
t159_ok:
t160: # sha512sig0 0xff00ff00ff00ff
    li   a0, 160
    li   a1, 0xff00ff00ff00ff
    sha512sig0 a3, a1
    li   t6, 0x7f7e817e817e817e
    beq  a3, t6, t160_ok
    j    fail
t160_ok:
t161: # sha512sig0 0x100000000
    li   a0, 161
    li   a1, 0x100000000
    sha512sig0 a3, a1
    li   t6, 0x83000000
    beq  a3, t6, t161_ok
    j    fail
t161_ok:
t162: # sha512sig0 0x8000000000000001
    li   a0, 162
    li   a1, 0x8000000000000001
    sha512sig0 a3, a1
    li   t6, 0xc080000000000000
    beq  a3, t6, t162_ok
    j    fail
t162_ok:
t163: # sha512sig0 0xffff8000
    li   a0, 163
    li   a1, 0xffff8000
    sha512sig0 a3, a1
    li   t6, 0x7effc080
    beq  a3, t6, t163_ok
    j    fail
t163_ok:
t164: # sha512sig0 0x102030400000080
    li   a0, 164
    li   a1, 0x102030400000080
    sha512sig0 a3, a1
    li   t6, 0x808207870c000041
    beq  a3, t6, t164_ok
    j    fail
t164_ok:
t165: # sha512sig0 0x6a09e667
    li   a0, 165
    li   a1, 0x6a09e667
    sha512sig0 a3, a1
    li   t6, 0xe700000035bae919
    beq  a3, t6, t165_ok
    j    fail
t165_ok:
t166: # sha512sig0 0x510e527f
    li   a0, 166
    li   a1, 0x510e527f
    sha512sig0 a3, a1
    li   t6, 0xff00000028743bc9
    beq  a3, t6, t166_ok
    j    fail
t166_ok:
t167: # sha512sig0 0x6a09e667f3bcc908
    li   a0, 167
    li   a1, 0x6a09e667f3bcc908
    sha512sig0 a3, a1
    li   t6, 0x3dbae91951caa1df
    beq  a3, t6, t167_ok
    j    fail
t167_ok:
t168: # sha512sig0 0x61626380
    li   a0, 168
    li   a1, 0x61626380
    sha512sig0 a3, a1
    li   t6, 0x8000000030129764
    beq  a3, t6, t168_ok
    j    fail
t168_ok:
t169: # sha512sig1 0x0
    li   a0, 169
    li   a1, 0x0
    sha512sig1 a3, a1
    li   t6, 0x0
    beq  a3, t6, t169_ok
    j    fail
t169_ok:
t170: # sha512sig1 0x1
    li   a0, 170
    li   a1, 0x1
    sha512sig1 a3, a1
    li   t6, 0x200000000008
    beq  a3, t6, t170_ok
    j    fail
t170_ok:
t171: # sha512sig1 0xffffffffffffffff
    li   a0, 171
    li   a1, 0xffffffffffffffff
    sha512sig1 a3, a1
    li   t6, 0x3ffffffffffffff
    beq  a3, t6, t171_ok
    j    fail
t171_ok:
t172: # sha512sig1 0x7
    li   a0, 172
    li   a1, 0x7
    sha512sig1 a3, a1
    li   t6, 0xe00000000038
    beq  a3, t6, t172_ok
    j    fail
t172_ok:
t173: # sha512sig1 0xfffffffffffffff9
    li   a0, 173
    li   a1, 0xfffffffffffffff9
    sha512sig1 a3, a1
    li   t6, 0x3ff3fffffffffcf
    beq  a3, t6, t173_ok
    j    fail
t173_ok:
t174: # sha512sig1 0x8000000000000000
    li   a0, 174
    li   a1, 0x8000000000000000
    sha512sig1 a3, a1
    li   t6, 0x200100000000004
    beq  a3, t6, t174_ok
    j    fail
t174_ok:
t175: # sha512sig1 0x7fffffffffffffff
    li   a0, 175
    li   a1, 0x7fffffffffffffff
    sha512sig1 a3, a1
    li   t6, 0x1ffeffffffffffb
    beq  a3, t6, t175_ok
    j    fail
t175_ok:
t176: # sha512sig1 0x80000000
    li   a0, 176
    li   a1, 0x80000000
    sha512sig1 a3, a1
    li   t6, 0x402001000
    beq  a3, t6, t176_ok
    j    fail
t176_ok:
t177: # sha512sig1 0x7fffffff
    li   a0, 177
    li   a1, 0x7fffffff
    sha512sig1 a3, a1
    li   t6, 0xffffe003fe000ff8
    beq  a3, t6, t177_ok
    j    fail
t177_ok:
t178: # sha512sig1 0xffffffff80000000
    li   a0, 178
    li   a1, 0xffffffff80000000
    sha512sig1 a3, a1
    li   t6, 0xfc001ffc01fff007
    beq  a3, t6, t178_ok
    j    fail
t178_ok:
t179: # sha512sig1 0x123456789abcdef0
    li   a0, 179
    li   a1, 0x123456789abcdef0
    sha512sig1 a3, a1
    li   t6, 0xa3460dbbd4317ac
    beq  a3, t6, t179_ok
    j    fail
t179_ok:
t180: # sha512sig1 0xfedcba9876543210
    li   a0, 180
    li   a1, 0xfedcba9876543210
    sha512sig1 a3, a1
    li   t6, 0x735cb9f2442bce85
    beq  a3, t6, t180_ok
    j    fail
t180_ok:
t181: # sha512sig1 0x3f
    li   a0, 181
    li   a1, 0x3f
    sha512sig1 a3, a1
    li   t6, 0x7e000000001f8
    beq  a3, t6, t181_ok
    j    fail
t181_ok:
t182: # sha512sig1 0x40
    li   a0, 182
    li   a1, 0x40
    sha512sig1 a3, a1
    li   t6, 0x8000000000201
    beq  a3, t6, t182_ok
    j    fail
t182_ok:
t183: # sha512sig1 0x21
    li   a0, 183
    li   a1, 0x21
    sha512sig1 a3, a1
    li   t6, 0x4200000000108
    beq  a3, t6, t183_ok
    j    fail
t183_ok:
t184: # sha512sig1 0xff00ff00ff00ff
    li   a0, 184
    li   a1, 0xff00ff00ff00ff
    sha512sig1 a3, a1
    li   t6, 0xe7e41be41be41be4
    beq  a3, t6, t184_ok
    j    fail
t184_ok:
t185: # sha512sig1 0x100000000
    li   a0, 185
    li   a1, 0x100000000
    sha512sig1 a3, a1
    li   t6, 0x804002000
    beq  a3, t6, t185_ok
    j    fail
t185_ok:
t186: # sha512sig1 0x8000000000000001
    li   a0, 186
    li   a1, 0x8000000000000001
    sha512sig1 a3, a1
    li   t6, 0x20030000000000c
    beq  a3, t6, t186_ok
    j    fail
t186_ok:
t187: # sha512sig1 0xffff8000
    li   a0, 187
    li   a1, 0xffff8000
    sha512sig1 a3, a1
    li   t6, 0xf0000007fc03e1ff
    beq  a3, t6, t187_ok
    j    fail
t187_ok:
t188: # sha512sig1 0x102030400000080
    li   a0, 188
    li   a1, 0x102030400000080
    sha512sig1 a3, a1
    li   t6, 0x804100c50608402
    beq  a3, t6, t188_ok
    j    fail
t188_ok:
t189: # sha512sig1 0x6a09e667
    li   a0, 189
    li   a1, 0x6a09e667
    sha512sig1 a3, a1
    li   t6, 0x3ccce00351e719e0
    beq  a3, t6, t189_ok
    j    fail
t189_ok:
t190: # sha512sig1 0x510e527f
    li   a0, 190
    li   a1, 0x510e527f
    sha512sig1 a3, a1
    li   t6, 0xca4fe0028936a090
    beq  a3, t6, t190_ok
    j    fail
t190_ok:
t191: # sha512sig1 0x6a09e667f3bcc908
    li   a0, 191
    li   a1, 0x6a09e667f3bcc908
    sha512sig1 a3, a1
    li   t6, 0xc8c619e73ee44510
    beq  a3, t6, t191_ok
    j    fail
t191_ok:
t192: # sha512sig1 0x61626380
    li   a0, 192
    li   a1, 0x61626380
    sha512sig1 a3, a1
    li   t6, 0x4c7000030a9699a2
    beq  a3, t6, t192_ok
    j    fail
t192_ok:
t193: # hsec.cteq 0x0, 0x0
    li   a0, 193
    li   a1, 0x0
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t193_ok
    j    fail
t193_ok:
t194: # hsec.cteq 0x1, 0x1
    li   a0, 194
    li   a1, 0x1
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t194_ok
    j    fail
t194_ok:
t195: # hsec.cteq 0xffffffffffffffff, 0xffffffffffffffff
    li   a0, 195
    li   a1, 0xffffffffffffffff
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t195_ok
    j    fail
t195_ok:
t196: # hsec.cteq 0x7, 0x7
    li   a0, 196
    li   a1, 0x7
    li   a2, 0x7
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t196_ok
    j    fail
t196_ok:
t197: # hsec.cteq 0xfffffffffffffff9, 0xfffffffffffffff9
    li   a0, 197
    li   a1, 0xfffffffffffffff9
    li   a2, 0xfffffffffffffff9
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t197_ok
    j    fail
t197_ok:
t198: # hsec.cteq 0x8000000000000000, 0x8000000000000000
    li   a0, 198
    li   a1, 0x8000000000000000
    li   a2, 0x8000000000000000
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t198_ok
    j    fail
t198_ok:
t199: # hsec.cteq 0x7fffffffffffffff, 0x7fffffffffffffff
    li   a0, 199
    li   a1, 0x7fffffffffffffff
    li   a2, 0x7fffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t199_ok
    j    fail
t199_ok:
t200: # hsec.cteq 0x80000000, 0x80000000
    li   a0, 200
    li   a1, 0x80000000
    li   a2, 0x80000000
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t200_ok
    j    fail
t200_ok:
t201: # hsec.cteq 0x7fffffff, 0x7fffffff
    li   a0, 201
    li   a1, 0x7fffffff
    li   a2, 0x7fffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t201_ok
    j    fail
t201_ok:
t202: # hsec.cteq 0xffffffff80000000, 0xffffffff80000000
    li   a0, 202
    li   a1, 0xffffffff80000000
    li   a2, 0xffffffff80000000
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t202_ok
    j    fail
t202_ok:
t203: # hsec.cteq 0x123456789abcdef0, 0x123456789abcdef0
    li   a0, 203
    li   a1, 0x123456789abcdef0
    li   a2, 0x123456789abcdef0
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t203_ok
    j    fail
t203_ok:
t204: # hsec.cteq 0xfedcba9876543210, 0xfedcba9876543210
    li   a0, 204
    li   a1, 0xfedcba9876543210
    li   a2, 0xfedcba9876543210
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t204_ok
    j    fail
t204_ok:
t205: # hsec.cteq 0x3f, 0x3f
    li   a0, 205
    li   a1, 0x3f
    li   a2, 0x3f
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t205_ok
    j    fail
t205_ok:
t206: # hsec.cteq 0x40, 0x40
    li   a0, 206
    li   a1, 0x40
    li   a2, 0x40
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t206_ok
    j    fail
t206_ok:
t207: # hsec.cteq 0x21, 0x21
    li   a0, 207
    li   a1, 0x21
    li   a2, 0x21
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t207_ok
    j    fail
t207_ok:
t208: # hsec.cteq 0x0, 0x0
    li   a0, 208
    li   a1, 0x0
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t208_ok
    j    fail
t208_ok:
t209: # hsec.cteq 0x0, 0xfedcba9876543210
    li   a0, 209
    li   a1, 0x0
    li   a2, 0xfedcba9876543210
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t209_ok
    j    fail
t209_ok:
t210: # hsec.cteq 0x1, 0xffffffffffffffff
    li   a0, 210
    li   a1, 0x1
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t210_ok
    j    fail
t210_ok:
t211: # hsec.cteq 0xffffffffffffffff, 0x1
    li   a0, 211
    li   a1, 0xffffffffffffffff
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t211_ok
    j    fail
t211_ok:
t212: # hsec.cteq 0x7, 0x0
    li   a0, 212
    li   a1, 0x7
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t212_ok
    j    fail
t212_ok:
t213: # hsec.cteq 0x7, 0x7
    li   a0, 213
    li   a1, 0x7
    li   a2, 0x7
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t213_ok
    j    fail
t213_ok:
t214: # hsec.cteq 0xfffffffffffffff9, 0x1
    li   a0, 214
    li   a1, 0xfffffffffffffff9
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t214_ok
    j    fail
t214_ok:
t215: # hsec.cteq 0xfffffffffffffff9, 0xffffffff80000000
    li   a0, 215
    li   a1, 0xfffffffffffffff9
    li   a2, 0xffffffff80000000
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t215_ok
    j    fail
t215_ok:
t216: # hsec.cteq 0x8000000000000000, 0xffffffffffffffff
    li   a0, 216
    li   a1, 0x8000000000000000
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t216_ok
    j    fail
t216_ok:
t217: # hsec.cteq 0x8000000000000000, 0x21
    li   a0, 217
    li   a1, 0x8000000000000000
    li   a2, 0x21
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t217_ok
    j    fail
t217_ok:
t218: # hsec.cteq 0x7fffffffffffffff, 0xffffffffffffffff
    li   a0, 218
    li   a1, 0x7fffffffffffffff
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t218_ok
    j    fail
t218_ok:
t219: # hsec.cteq 0x80000000, 0x0
    li   a0, 219
    li   a1, 0x80000000
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t219_ok
    j    fail
t219_ok:
t220: # hsec.cteq 0x80000000, 0x80000000
    li   a0, 220
    li   a1, 0x80000000
    li   a2, 0x80000000
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t220_ok
    j    fail
t220_ok:
t221: # hsec.cteq 0x7fffffff, 0x1
    li   a0, 221
    li   a1, 0x7fffffff
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t221_ok
    j    fail
t221_ok:
t222: # hsec.cteq 0x7fffffff, 0x7fffffff
    li   a0, 222
    li   a1, 0x7fffffff
    li   a2, 0x7fffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t222_ok
    j    fail
t222_ok:
t223: # hsec.cteq 0xffffffff80000000, 0xffffffffffffffff
    li   a0, 223
    li   a1, 0xffffffff80000000
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t223_ok
    j    fail
t223_ok:
t224: # hsec.cteq 0x123456789abcdef0, 0x0
    li   a0, 224
    li   a1, 0x123456789abcdef0
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t224_ok
    j    fail
t224_ok:
t225: # hsec.cteq 0x123456789abcdef0, 0x7fffffffffffffff
    li   a0, 225
    li   a1, 0x123456789abcdef0
    li   a2, 0x7fffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t225_ok
    j    fail
t225_ok:
t226: # hsec.cteq 0xfedcba9876543210, 0x1
    li   a0, 226
    li   a1, 0xfedcba9876543210
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t226_ok
    j    fail
t226_ok:
t227: # hsec.cteq 0x3f, 0x0
    li   a0, 227
    li   a1, 0x3f
    li   a2, 0x0
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t227_ok
    j    fail
t227_ok:
t228: # hsec.cteq 0x3f, 0x8000000000000000
    li   a0, 228
    li   a1, 0x3f
    li   a2, 0x8000000000000000
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t228_ok
    j    fail
t228_ok:
t229: # hsec.cteq 0x40, 0x1
    li   a0, 229
    li   a1, 0x40
    li   a2, 0x1
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t229_ok
    j    fail
t229_ok:
t230: # hsec.cteq 0x40, 0x40
    li   a0, 230
    li   a1, 0x40
    li   a2, 0x40
    hsec.cteq a3, a1, a2
    li   t6, 0x1
    beq  a3, t6, t230_ok
    j    fail
t230_ok:
t231: # hsec.cteq 0x21, 0xffffffffffffffff
    li   a0, 231
    li   a1, 0x21
    li   a2, 0xffffffffffffffff
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t231_ok
    j    fail
t231_ok:
t232: # hsec.cteq, operands differ only in bit 0
    li   a0, 232
    li   a1, 0x0123456789abcdef
    li   a2, 0x123456789abcdee
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t232_ok
    j    fail
t232_ok:
t233: # hsec.cteq, operands differ only in bit 31
    li   a0, 233
    li   a1, 0x0123456789abcdef
    li   a2, 0x123456709abcdef
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t233_ok
    j    fail
t233_ok:
t234: # hsec.cteq, operands differ only in bit 32
    li   a0, 234
    li   a1, 0x0123456789abcdef
    li   a2, 0x123456689abcdef
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t234_ok
    j    fail
t234_ok:
t235: # hsec.cteq, operands differ only in bit 63
    li   a0, 235
    li   a1, 0x0123456789abcdef
    li   a2, 0x8123456789abcdef
    hsec.cteq a3, a1, a2
    li   t6, 0x0
    beq  a3, t6, t235_ok
    j    fail
t235_ok:
t236: # sha256sig0 result forwarded to the very next instruction
    li   a0, 236
    li   t0, 0x61626380
    sha256sig0 t1, t0
    xor  a3, t1, zero
    li   t6, 0xffffffff940e90ef
    beq  a3, t6, t236_ok
    j    fail
t236_ok:
t237: # rs2 of hsec.cteq forwarded from the instruction just before
    li   a0, 237
    li   t0, 0x5a5a
    li   t1, 0x5a5a
    hsec.cteq a3, t0, t1
    li   t6, 0x1
    beq  a3, t6, t237_ok
    j    fail
t237_ok:
t238: # rs2 of hsec.cteq LOADED by the instruction just before: the load-use stall needs USES_REGISTER2 for custom-0
    li   a0, 238
    la   s0, scratch
    li   t0, 0x5a5a
    sd   t0, 0(s0)
    ld   t1, 0(s0)
    hsec.cteq a3, t0, t1
    li   t6, 0x1
    beq  a3, t6, t238_ok
    j    fail
t238_ok:
t239: # hsec.cteq result used as a branch condition
    li   a0, 239
    li   t0, 7
    li   t1, 7
    hsec.cteq t2, t0, t1
    li   a3, 0
    beqz t2, t239_skip
    li   a3, 1
t239_skip:
    li   t6, 0x1
    beq  a3, t6, t239_ok
    j    fail
t239_ok:
t240: # other custom-0 patterns write nothing (funct3 = 111)
    li   a0, 240
    li   a3, 42
    .word 0x00c5f68b
    mv   a3, a3
    li   t6, 0x2a
    beq  a3, t6, t240_ok
    j    fail
t240_ok:
pass:
    li   a0, 0
    halt               # tohost = 1: PASS
fail:
    slli t0, a0, 1     # a0 holds the failing test number
    ori  t0, t0, 1
    csrw tohost, t0    # tohost = (n << 1) | 1: FAIL in test n
    j    .

    .align 3
scratch:
    .zero 16
