# =============================================================================
# 23_sha256.s: SHA-256 with and without the Zknh instructions
#
# Hashes "abc" (one 64-byte block, padded here by hand) twice: once with the
# four Zknh instructions, sha256sum0/sum1/sig0/sig1, and once with the same
# functions built from shifts and ORs. Both digests are checked against the
# FIPS 180-4 answer, ba7816bf...f20015ad.
#
# This is the program behind docs/ADDING_INSTRUCTIONS.md: the instructions it
# uses were added to Sixfold one layer at a time, and this is how you show
# they were worth adding.
#
#   a3 : digest words correct with Zknh (8 of 8)
#   a4 : digest words correct without   (8 of 8)
#   a5 : cycles with Zknh
#   a6 : cycles without
# Generated by a script; the test compares every register below on RTL and model.
# EXPECT: a3 = 8
# EXPECT: a4 = 8
# =============================================================================
    rdcycle s0
    jal  ra, sha_zknh
    rdcycle s1
    sub  a5, s1, s0
    jal  ra, count_ok
    mv   a3, a0
    rdcycle s0
    jal  ra, sha_rv64
    rdcycle s1
    sub  a6, s1, s0
    jal  ra, count_ok
    mv   a4, a0
    halt

count_ok:              # a0 = how many digest words match the expected value
    la   t0, digest
    la   t1, expected
    li   a0, 0
    li   t2, 8
count_loop:
    lw   t3, 0(t0)
    lw   t4, 0(t1)
    bne  t3, t4, count_skip
    addi a0, a0, 1
count_skip:
    addi t0, t0, 4
    addi t1, t1, 4
    addi t2, t2, -1
    bnez t2, count_loop
    ret

sha_zknh:                # with Zknh: each sigma is ONE instruction
    la   t0, h_init
    lw   s2, 0(t0)
    lw   s3, 4(t0)
    lw   s4, 8(t0)
    lw   s5, 12(t0)
    lw   s6, 16(t0)
    lw   s7, 20(t0)
    lw   s8, 24(t0)
    lw   s9, 28(t0)
    # message schedule: W[16..63] from W[0..15]
    la   s10, w
    li   t0, 64
    li   t5, 256
sha_zknh_sched:
    add  t1, s10, t0
    lw   t2, -8(t1)        # W[t-2]
    lw   t3, -60(t1)       # W[t-15]
    sha256sig1 a0, t2
    sha256sig0 a1, t3
    lw   t2, -28(t1)       # W[t-7]
    lw   t3, -64(t1)       # W[t-16]
    addw a0, a0, a1
    addw a0, a0, t2
    addw a0, a0, t3
    sw   a0, 0(t1)
    addi t0, t0, 4
    bne  t0, t5, sha_zknh_sched
    # 64 rounds of compression
    la   s11, k
    li   t0, 0
sha_zknh_round:
    add  t1, s11, t0
    lw   t2, 0(t1)         # K[t]
    add  t1, s10, t0
    lw   t3, 0(t1)         # W[t]
    addw t4, s9, t2
    addw t4, t4, t3
    sha256sum1 a0, s6
    addw t4, t4, a0
    and  a1, s6, s7
    andn a2, s8, s6       # Ch = (e & f) ^ (~e & g)
    xor  a1, a1, a2
    addw t4, t4, a1   # T1
    sha256sum0 a0, s2
    and  a1, s2, s3
    and  a2, s2, s4
    xor  a1, a1, a2
    and  a2, s3, s4
    xor  a1, a1, a2   # Maj
    addw a0, a0, a1   # T2
    mv   s9, s8
    mv   s8, s7
    mv   s7, s6
    addw s6, s5, t4
    mv   s5, s4
    mv   s4, s3
    mv   s3, s2
    addw s2, t4, a0
    addi t0, t0, 4
    bne  t0, t5, sha_zknh_round
    # digest = H0 + working variables
    la   t0, h_init
    la   t1, digest
    lw   t2, 0(t0)
    addw t2, t2, s2
    sw   t2, 0(t1)
    lw   t2, 4(t0)
    addw t2, t2, s3
    sw   t2, 4(t1)
    lw   t2, 8(t0)
    addw t2, t2, s4
    sw   t2, 8(t1)
    lw   t2, 12(t0)
    addw t2, t2, s5
    sw   t2, 12(t1)
    lw   t2, 16(t0)
    addw t2, t2, s6
    sw   t2, 16(t1)
    lw   t2, 20(t0)
    addw t2, t2, s7
    sw   t2, 20(t1)
    lw   t2, 24(t0)
    addw t2, t2, s8
    sw   t2, 24(t1)
    lw   t2, 28(t0)
    addw t2, t2, s9
    sw   t2, 28(t1)
    ret

sha_rv64:                # plain RV64I + Zbb: each sigma is 8 to 11 instructions
    la   t0, h_init
    lw   s2, 0(t0)
    lw   s3, 4(t0)
    lw   s4, 8(t0)
    lw   s5, 12(t0)
    lw   s6, 16(t0)
    lw   s7, 20(t0)
    lw   s8, 24(t0)
    lw   s9, 28(t0)
    # message schedule: W[16..63] from W[0..15]
    la   s10, w
    li   t0, 64
    li   t5, 256
sha_rv64_sched:
    add  t1, s10, t0
    lw   t2, -8(t1)        # W[t-2]
    lw   t3, -60(t1)       # W[t-15]
    srliw a6, t2, 17
    slliw a7, t2, 15
    or   a0, a6, a7
    srliw a6, t2, 19
    slliw a7, t2, 13
    or   t6, a6, a7
    xor  a0, a0, t6
    srliw t6, t2, 10
    xor  a0, a0, t6
    srliw a6, t3, 7
    slliw a7, t3, 25
    or   a1, a6, a7
    srliw a6, t3, 18
    slliw a7, t3, 14
    or   t6, a6, a7
    xor  a1, a1, t6
    srliw t6, t3, 3
    xor  a1, a1, t6
    lw   t2, -28(t1)       # W[t-7]
    lw   t3, -64(t1)       # W[t-16]
    addw a0, a0, a1
    addw a0, a0, t2
    addw a0, a0, t3
    sw   a0, 0(t1)
    addi t0, t0, 4
    bne  t0, t5, sha_rv64_sched
    # 64 rounds of compression
    la   s11, k
    li   t0, 0
sha_rv64_round:
    add  t1, s11, t0
    lw   t2, 0(t1)         # K[t]
    add  t1, s10, t0
    lw   t3, 0(t1)         # W[t]
    addw t4, s9, t2
    addw t4, t4, t3
    srliw a6, s6, 6
    slliw a7, s6, 26
    or   a0, a6, a7
    srliw a6, s6, 11
    slliw a7, s6, 21
    or   t6, a6, a7
    xor  a0, a0, t6
    srliw a6, s6, 25
    slliw a7, s6, 7
    or   t6, a6, a7
    xor  a0, a0, t6
    addw t4, t4, a0
    and  a1, s6, s7
    andn a2, s8, s6       # Ch = (e & f) ^ (~e & g)
    xor  a1, a1, a2
    addw t4, t4, a1   # T1
    srliw a6, s2, 2
    slliw a7, s2, 30
    or   a0, a6, a7
    srliw a6, s2, 13
    slliw a7, s2, 19
    or   t6, a6, a7
    xor  a0, a0, t6
    srliw a6, s2, 22
    slliw a7, s2, 10
    or   t6, a6, a7
    xor  a0, a0, t6
    and  a1, s2, s3
    and  a2, s2, s4
    xor  a1, a1, a2
    and  a2, s3, s4
    xor  a1, a1, a2   # Maj
    addw a0, a0, a1   # T2
    mv   s9, s8
    mv   s8, s7
    mv   s7, s6
    addw s6, s5, t4
    mv   s5, s4
    mv   s4, s3
    mv   s3, s2
    addw s2, t4, a0
    addi t0, t0, 4
    bne  t0, t5, sha_rv64_round
    # digest = H0 + working variables
    la   t0, h_init
    la   t1, digest
    lw   t2, 0(t0)
    addw t2, t2, s2
    sw   t2, 0(t1)
    lw   t2, 4(t0)
    addw t2, t2, s3
    sw   t2, 4(t1)
    lw   t2, 8(t0)
    addw t2, t2, s4
    sw   t2, 8(t1)
    lw   t2, 12(t0)
    addw t2, t2, s5
    sw   t2, 12(t1)
    lw   t2, 16(t0)
    addw t2, t2, s6
    sw   t2, 16(t1)
    lw   t2, 20(t0)
    addw t2, t2, s7
    sw   t2, 20(t1)
    lw   t2, 24(t0)
    addw t2, t2, s8
    sw   t2, 24(t1)
    lw   t2, 28(t0)
    addw t2, t2, s9
    sw   t2, 28(t1)
    ret

    .align 3
h_init:
    .word 0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
expected:
    .word 0xba7816bf, 0x8f01cfea, 0x414140de, 0x5dae2223, 0xb00361a3, 0x96177a9c, 0xb410ff61, 0xf20015ad
digest:
    .zero 32
k:
    .word 0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5
    .word 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174
    .word 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da
    .word 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967
    .word 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85
    .word 0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070
    .word 0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3
    .word 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
w:                     # W[0..15] is the padded block; W[16..63] is filled in
    .word 0x61626380, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000
    .word 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000018
    .zero 192
